import { AdminData } from "../TAdminData";

export const defaultAdminObject: AdminData = {
  contractNumber: "",
  estimator: "",
  division: null,
  lettingDate: null,
  owner: null,
  county: {
    country: "",  // Aquí debe estar el campo country
    id: 0,
    name: "",
    district: 0,
    branch: "",
    laborRate: 0,
    fringeRate: 0,
    shopRate: 0,
    flaggingRate: 0,
    flaggingBaseRate: 0,
    flaggingFringeRate: 0,
    ratedTargetGM: 0,
    nonRatedTargetGM: 0,
    insurance: 0,
    fuel: 0,
    market: "LOCAL",
  },
  srRoute: "",
  location: "",
  dbe: "",
  startDate: null,
  endDate: null,
  winterStart: undefined,
  winterEnd: undefined,
  owTravelTimeHours: 0,
  owTravelTimeMinutes: 0,
  owMileage: 0,
  fuelCostPerGallon: 0,
  rated: "RATED",
  emergencyJob: false,
  emergencyFields: {
    emergencyHIVerticalPanels: 0,
    emergencyTypeXIVerticalPanels: 0,
    emergencyBLites: 0,
    emergencyACLites: 0,
    emergencySharps: 0,
  },
};
